services:
  - type: web
    name: spis-ml
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: cd dashboard && gunicorn -w 1 -b 0.0.0.0:$PORT app:server
